# Generated by Django 4.1.2 on 2022-12-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_upload_title_alter_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.upload')),
            ],
        ),
    ]
